export const comunidadesAutonomas = {
    Andalucía: [
      "Almería",
      "Cádiz",
      "Córdoba",
      "Granada",
      "Huelva",
      "Jaén",
      "Málaga",
      "Sevilla",
    ],
    Aragón: ["Huesca", "Teruel", "Zaragoza"],
    Asturias: ["Asturias"],
    "Islas Baleares": ["Islas Baleares"],
    Canarias: ["Las Palmas", "Santa Cruz de Tenerife"],
    Cantabria: ["Cantabria"],
    "Castilla-La Mancha": [
      "Albacete",
      "Ciudad Real",
      "Cuenca",
      "Guadalajara",
      "Toledo",
    ],
    "Castilla y León": [
      "Ávila",
      "Burgos",
      "León",
      "Palencia",
      "Salamanca",
      "Segovia",
      "Soria",
      "Valladolid",
      "Zamora",
    ],
    Catalunia: ["Barcelona", "Girona", "Lleida", "Tarragona"],
    "Comunidad Valenciana": ["Alicante", "Castellón", "Valencia"],
    Extremadura: ["Badajoz", "Cáceres"],
    Galicia: ["A Coruña", "Lugo", "Ourense", "Pontevedra"],
    "La Rioja": ["La Rioja"],
    "Comunidad de Madrid": ["Madrid"],
    "Región de Murcia": ["Murcia"],
    Navarra: ["Navarra"],
    "País Vasco": ["Álava", "Guipúzcoa", "Vizcaya"],
  };